// Generated by CoffeeScript 1.6.3
(function() {
  var env, html, http, iconv, options, post_data, querystring, req;

  env = (require('jsdom')).env;

  http = require('http');

  querystring = require('querystring');

  iconv = require('iconv-lite');

  html = '';

  options = {
    hostname: "e.tju.edu.cn",
    port: 80,
    path: "/Education/schedule.do?schekind=6",
    method: 'POST'
  };

  post_data = querystring.stringify({
    todo: 'displayWeekBuilding',
    week: 1,
    building_no: '0022'
  });

  req = http.request(options, function(res) {
    res.setEncoding('utf8');
    res.on('data', function(chunk) {
      return html += chunk;
    });
    return res.on('end', function() {
      return env(html, function(err, window) {
        var $;
        return $ = (require('jquery'))(window);
      });
    });
  });

  req.write("" + post_data + "\n");

  req.end();

}).call(this);
